# Generated by Django 5.2.9 on 2026-09-05 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('registration_number', models.CharField(max_length=255, verbose_name='Registration Number')),
                ('company_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('llc', 'LLC')], default='private', max_length=20, verbose_name='Company Type')),
                ('industry', models.CharField(max_length=150, verbose_name='Industry')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('province', models.CharField(max_length=130, verbose_name='Province')),
                ('district', models.CharField(max_length=120, verbose_name='District')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('full_address', models.TextField(verbose_name='Full Address')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Representative Name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('phone', models.CharField(max_length=15, verbose_name='Representative Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Representative Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Representative',
                'verbose_name_plural': 'Representatives',
            },
        ),
    ]
