# Generated by Django 5.2.9 on 2026-09-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_companyrepresentative_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateNumber', models.CharField(max_length=100, unique=True, verbose_name='شماره گواهی')),
                ('registrationNo', models.CharField(max_length=100, verbose_name='شماره ثبت')),
                ('issueDate', models.DateField(verbose_name='تاریخ صدور')),
                ('phytosanitaryNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرنطینه نباتی')),
                ('plateNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پلاک وسیله نقلیه')),
                ('containerNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره کانتینر')),
                ('countryOfOrigin', models.CharField(max_length=100, verbose_name='کشور مبدا')),
                ('countryOfDestination', models.CharField(max_length=100, verbose_name='کشور مقصد')),
                ('portOfLoading', models.CharField(blank=True, max_length=100, null=True, verbose_name='بندر بارگیری')),
                ('quantity', models.CharField(max_length=100, verbose_name='مقدار / تعداد')),
                ('commodity', models.CharField(max_length=255, verbose_name='نوع کالا / محصول')),
                ('consignmentLink', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک محموله')),
                ('exporterName', models.CharField(max_length=255, verbose_name='نام صادرکننده')),
                ('exporterAddress', models.TextField(verbose_name='آدرس صادرکننده')),
                ('importerName', models.CharField(max_length=255, verbose_name='نام واردکننده')),
                ('importerAddress', models.TextField(verbose_name='آدرس واردکننده')),
                ('treatmentType', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع فرآوری')),
                ('fumigantType', models.CharField(blank=True, max_length=100, null=True, verbose_name='ماده ضدعفونی کننده')),
                ('prescribedDose', models.CharField(blank=True, max_length=100, null=True, verbose_name='دوز تجویز شده')),
                ('appliedDose', models.CharField(blank=True, max_length=100, null=True, verbose_name='دوز اعمال شده')),
                ('minTemperature', models.CharField(blank=True, max_length=50, null=True, verbose_name='حداقل دما')),
                ('exposurePeriod', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدت زمان قرارگیری')),
                ('dateOfFumigation', models.DateField(blank=True, null=True, verbose_name='تاریخ ضدعفونی')),
                ('placeOfFumigation', models.CharField(blank=True, max_length=255, null=True, verbose_name='محل ضدعفونی')),
                ('fumigatorLicense', models.CharField(blank=True, max_length=100, null=True, verbose_name='مجوز ضدعفونی کننده')),
                ('accreditationNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره اعتبارنامه')),
                ('exporterInvoiceNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره فاکتور صادرکننده')),
                ('billOfLadingNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره بارنامه / CMR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='company.company', verbose_name='کمپانی صادرکننده')),
            ],
        ),
    ]
